#!/bin/sh -e

if [ -z ${1} ]; then
	echo "Script that stashes/stash pop changes when you checkout"
	echo -e "\nUsage:"
	echo "  git c <arguments>"

	exit 1;
fi

git stash && git checkout "$@" && git stash pop
