#!/bin/sh -e

if [ -z ${1} ]; then
	echo "Script to update specified branch, rebase on it, checkout to it, merge previous branch, push, delete prev branch on local and origin"
	echo -e "\nUsage:"
	echo "  git m <branch>"

	exit 1;
fi

prev_branch=$(git symbolic-ref -q HEAD --short)
branch=${1}
git f ${branch} && \
git rebase ${branch} && \
git checkout ${branch}  && \
git merge ${prev_branch} && \
git push && \
git branch -d ${prev_branch} && \
git push origin --delete ${prev_branch}
